### PR TITLE
Add autoload-dev so users can use Fakeresponse sender when needed on tes...

### PR DESCRIPTION
**Pull request by harikt**
...ting

### CODE REVIEW

**Comment by harikt** [comment]
@pmjones what are your thoughts on adding to autoload-dev ?

Can I merge this ?

**Comment by mbrevda** [comment]
@pmjones +1

**Comment by pmjones** [comment]
Overcoming my initial resistance to this. ;-)

**Comment by mbrevda** [comment]
:clap:

**Comment by harikt** [comment]
I was thinking the other day, the `FakeResponse`, `FakeSessionHandler` etc should move to `src`, and promote using it for testing. Else people will have hard time to figure how to test .

**Pull request merged**
