### PR TITLE
Support multiple header values.

### PR DESCRIPTION
**Pull request by ralouphie**
Added `Response/Headers::add` to give the ability to set multiple values for a given header.

### CODE REVIEW

**Comment by ralouphie** [comment]
Not sure why Scrutinizer failed here.

**Comment by harikt** [comment]
@ralouphie not your problem . code coverage was not received from travis. Thank you for the PR.

**Comment by ralouphie** [comment]
Any feedback for this PR? Anything you would like to see changed?

**Comment by harikt** [comment]
@ralouphie I am :+1: for this. Thanks!

**Comment by ralouphie** [comment]
Is this package still being maintained?

**Comment by pmjones** [comment]
It is, but I am pulled in several directions at once, and cannot always respond in a timely manner when a non-trivial improvement is proposed that requires my full attention. I do promise that it _will_ get my full attention, I just don't know when. Thanks in advance for your patience.

**Pull request merged**
